export QT_SELECT=5
export AURDEST=/home/neil/arch/builds
export BROWSER='nelinks'
export BUILDDIR=/home/neil/arch/builds
export SRCDEST=/home/neil/arch/sources
#export CCACHE_PATH=/usr/bin
export EDITOR='emacsclient -c '
export ELINKS_XTERM='/usr/bin/x-terminal-emulator'
export GIT_EDITOR='emacsclient -nw '
export HISTCONTROL=ignoreboth
export HISTFILE=~/.histfile
export HISTSIZE=2000
export MAILDIR=~/Maildir/
export SAVEHIST=2000
export IRCNICK=daedalux
export LC_COLLATE=C
export LESS='-ceaisMRJwj.3'
export LESSEDIT='emacsclient -nw  ?lm+%lm. %f '
export MAILPATH='/home/neil/Mail/mbox:/var/mail/neil'
#export MANWIDTH=80
export NNTPSERVER=news.eternal-september.org
export QT_QPA_PLATFORMTHEME="qt5ct"
# export QT_STYLE_OVERRIDE=gtk
export QUOTING_STYLE=literal
# use this if starting ssh-agent from systemd --user
export SSH_AUTH_SOCK="$XDG_RUNTIME_DIR/ssh-agent.socket"
export SSH_AGENT_PID=$(pgrep -u neil ssh-agent)
export TINRC='-r -A'
export YAOURT_COLORS="nb=1:pkg=1:ver=1;32:lver=1;45:installed=1;42:grp=1;34:od=1;41;5:votes=1;44:dsc=0:other=1;35"
